# Front Matterのデフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      display_order: 0

################################## IT記事
  - scope:
      path: "_it_articles"
    values:
      layout: "it"
      category: "IT"

# IT記事のサブカテゴリ
  - scope:
      path: "_it_articles/access"
    values:
      sub_category: "Access"
  - scope:
      path: "_it_articles/chrome"
    values:
      sub_category: "Chrome"
  - scope:
      path: "_it_articles/database"
    values:
      sub_category: "Database"
  - scope:
      path: "_it_articles/go"
    values:
      sub_category: "Go"
  - scope:
      path: "_it_articles/java"
    values:
      sub_category: "Java"
  - scope:
      path: "_it_articles/linux"
    values:
      sub_category: Linux
  - scope:
      path: "_it_articles/oracle"
    values:
      sub_category: "Oracle"
  - scope:
      path: "_it_articles/other"
    values:
      sub_category: "その他"
  - scope:
      path: "_it_articles/powershell"
    values:
      sub_category: PowerShell
  - scope:
      path: "_it_articles/sqlserver"
    values:
      sub_category: "SQL Server"
  - scope:
      path: "_it_articles/subversion"
    values:
      sub_category: "Subversion"
  - scope:
      path: "_it_articles/teams"
    values:
      sub_category: "Teams"
  - scope:
      path: "_it_articles/vba"
    values:
      sub_category: "VBA"
  - scope:
      path: "_it_articles/vscode"
    values:
      sub_category: "VSCode"

################################## 読書
  - scope:
      path: "_reading_articles"
    values:
      layout: "reading"
      category: "Reading"

# 読書のサブカテゴリ
# 読書法
  - scope:
      path: "_reading_articles/method"
    values:
      sub_category: "読書法"

# コレクションの設定
collections_dir: collections

collections:
  # 更新履歴
  history:
    output: false

  # IT記事
  it_articles:
    output: true
    permalink: /it/:path

  # 読書の記事
  reading_articles:
    output: true
    permalink: /reading/:path
