# Front Matterのデフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default_layout"
      display_order: 0

################################## IT記事
  - scope:
      path: "_it_articles"
    values:
      layout: "it_article_layout"
      category_id: "it"

# IT記事のサブカテゴリ
  - scope:
      path: "_it_articles/access"
    values:
      sub_category_id: "access"

  # C言語
  - scope:
      path: "_it_articles/c"
    values:
      sub_category_id: "c"

  - scope:
      path: "_it_articles/chrome"
    values:
      sub_category_id: "chrome"
  - scope:
      path: "_it_articles/database"
    values:
      sub_category_id: "database"
  - scope:
      path: "_it_articles/excel"
    values:
      sub_category_id: "excel"
  - scope:
      path: "_it_articles/go"
    values:
      sub_category_id: "go"

  # Gradle
  - scope:
      path: "_it_articles/gradle"
    values:
      sub_category_id: "gradle"

  # Groovy
  - scope:
      path: "_it_articles/groovy"
    values:
      sub_category_id: "groovy"

  - scope:
      path: "_it_articles/git"
    values:
      sub_category_id: "git"

  - scope:
      path: "_it_articles/java"
    values:
      sub_category_id: "java"

  # Julia
  - scope:
      path: "_it_articles/julia"
    values:
      sub_category_id: "julia"

  - scope:
      path: "_it_articles/linux"
    values:
      sub_category_id: linux

  # Kotlin
  - scope:
      path: "_it_articles/kotlin"
    values:
      sub_category_id: kotlin

  # Liquid
  - scope:
      path: "_it_articles/liquid"
    values:
      sub_category_id: liquid

  - scope:
      path: "_it_articles/oracle"
    values:
      sub_category_id: "oracle"

  # テスト
  - scope:
      path: "_it_articles/test"
    values:
      sub_category_id: "test"

  # その他
  - scope:
      path: "_it_articles/other"
    values:
      sub_category_id: "other"

  # Outlook
  - scope:
      path: "_it_articles/outlook"
    values:
      sub_category_id: "outlook"

  - scope:
      path: "_it_articles/structured_text_data_format"
    values:
      sub_category_id: "structured_text_data_format"
  - scope:
      path: "_it_articles/problem"
    values:
      sub_category_id: "problem"
  - scope:
      path: "_it_articles/powershell"
    values:
      sub_category_id: powershell
  - scope:
      path: "_it_articles/python"
    values:
      sub_category_id: python
  - scope:
      path: "_it_articles/ruby"
    values:
      sub_category_id: ruby
  - scope:
      path: "_it_articles/sqlserver"
    values:
      sub_category_id: "sqlserver"
  - scope:
      path: "_it_articles/subversion"
    values:
      sub_category_id: "subversion"

  # サクラエディタ
  - scope:
      path: "_it_articles/sakuraeditor"
    values:
      sub_category_id: "sakuraeditor"

  - scope:
      path: "_it_articles/teams"
    values:
      sub_category_id: "teams"
  - scope:
      path: "_it_articles/vba"
    values:
      sub_category_id: "vba"
  - scope:
      path: "_it_articles/vscode"
    values:
      sub_category_id: "vscode"
  - scope:
      path: "_it_articles/windows"
    values:
      sub_category_id: "windows"
  - scope:
      path: "_it_articles/windows_batch"
    values:
      sub_category_id: windows_batch

################################## 人生
  - scope:
      path: "_life_articles"
    values:
      layout: "life_article_layout"
      category_id: "life"

# 人生のサブカテゴリ
  # 断捨離
  - scope:
      path: "_life_articles/minimalism"
    values:
      sub_category_id: "minimalism"

  # 態度
  - scope:
      path: "_life_articles/attitude"
    values:
      sub_category_id: "attitude"

  # 目的
  - scope:
      path: "_life_articles/purpose"
    values:
      sub_category_id: "purpose"

  # 失敗
  - scope:
      path: "_life_articles/failure"
    values:
      sub_category_id: "failure"

  # 成功
  - scope:
      path: "_life_articles/success"
    values:
      sub_category_id: "success"

  # 時間管理
  - scope:
      path: "_life_articles/time_management"
    values:
      sub_category_id: "time_management"

  # 食事について
  - scope:
      path: "_life_articles/eat"
    values:
      sub_category_id: "eat"

  # 幸せについて
  - scope:
      path: "_life_articles/happiness"
    values:
      sub_category_id: "happiness"

  # 運について
  - scope:
      path: "_life_articles/luck"
    values:
      sub_category_id: "luck"

  # 人間関係について
  - scope:
      path: "_life_articles/human_relations"
    values:
      sub_category_id: "human_relations"

  # 意識と無意識について
  - scope:
      path: "_life_articles/consciousness_and_unconsciousness"
    values:
      sub_category_id: "consciousness_and_unconsciousness"

################################## 読書
  - scope:
      path: "_reading_articles"
    values:
      layout: "reading_article_layout"
      category_id: "reading"

# 読書のサブカテゴリ
  # 読書の魅力
  - scope:
      path: "_reading_articles/charmpoint"
    values:
      sub_category_id: "charmpoint"
  # 読書法
  - scope:
      path: "_reading_articles/method"
    values:
      sub_category_id: "method"

################################## 科学
  - scope:
      path: "_science_articles"
    values:
      layout: "science_article_layout"
      category_id: "science"

# 科学のメモのサブカテゴリ
  # 物理学のメモ
  - scope:
      path: "_science_articles/physics"
    values:
      sub_category_id: "physics"

  # 心理学のメモ
  - scope:
      path: "_science_articles/psychology"
    values:
      sub_category_id: "psychology"

  # パラドックスのメモ
  - scope:
      path: "_science_articles/paradox"
    values:
      sub_category_id: "paradox"

################################## 経済
  - scope:
      path: "_economy_articles"
    values:
      layout: "economy_article_layout"
      category_id: "economy"

# 経済についてのメモのサブカテゴリ
  # 投資についてのメモ
  - scope:
      path: "_economy_articles/investment"
    values:
      sub_category_id: "investment"

################################## 全メモのリスト
  - scope:
      path: "all"
    values:
      layout: "all_layout"
      category_id: "all"

# コレクションの設定
collections_dir: collections

collections:
  # 更新履歴
  history:

  # IT記事
  it_articles:
    output: true
    permalink: /it/:path

  # 人生の記事
  life_articles:
    output: true
    permalink: /life/:path

  # 読書の記事
  reading_articles:
    output: true
    permalink: /reading/:path

  # 科学の記事
  science_articles:
    output: true
    permalink: /science/:path

  # 経済の記事
  economy_articles:
    output: true
    permalink: /economy/:path

# 除外ファイル/ディレクトリ
exclude:
  - _articles
  - _draft
  - _scripts
  - .work
  - build.gradle
  - gradle
  - gradlew
  - gradlew.bat
