defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "programming"
    values:
      layout: "programming"
      category: "Programming"
  -
    scope:
      path: "database"
    values:
      layout: "database"
      category: "Database"
