# Front Matterのデフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default_layout"
      display_order: 0

################################## IT記事
  - scope:
      path: "_it_articles"
    values:
      layout: "it_article_layout"
      category_id: "it"

# IT記事のサブカテゴリ
  - scope:
      path: "_it_articles/access"
    values:
      sub_category_id: "access"
  - scope:
      path: "_it_articles/chrome"
    values:
      sub_category_id: "chrome"
  - scope:
      path: "_it_articles/database"
    values:
      sub_category_id: "database"
  - scope:
      path: "_it_articles/excel"
    values:
      sub_category_id: "excel"
  - scope:
      path: "_it_articles/go"
    values:
      sub_category_id: "go"
  - scope:
      path: "_it_articles/git"
    values:
      sub_category_id: "git"
  - scope:
      path: "_it_articles/java"
    values:
      sub_category_id: "java"
  - scope:
      path: "_it_articles/linux"
    values:
      sub_category_id: linux
  - scope:
      path: "_it_articles/oracle"
    values:
      sub_category_id: "oracle"
  - scope:
      path: "_it_articles/other"
    values:
      sub_category_id: "other"
  - scope:
      path: "_it_articles/problem"
    values:
      sub_category_id: "problem"
  - scope:
      path: "_it_articles/powershell"
    values:
      sub_category_id: powershell
  - scope:
      path: "_it_articles/python"
    values:
      sub_category_id: python
  - scope:
      path: "_it_articles/ruby"
    values:
      sub_category_id: ruby
  - scope:
      path: "_it_articles/sqlserver"
    values:
      sub_category_id: "sqlserver"
  - scope:
      path: "_it_articles/subversion"
    values:
      sub_category_id: "subversion"
  - scope:
      path: "_it_articles/teams"
    values:
      sub_category_id: "teams"
  - scope:
      path: "_it_articles/vba"
    values:
      sub_category_id: "vba"
  - scope:
      path: "_it_articles/vscode"
    values:
      sub_category_id: "vscode"
  - scope:
      path: "_it_articles/windows"
    values:
      sub_category_id: "windows"

################################## 科学
  - scope:
      path: "_science_articles"
    values:
      layout: "science_article_layout"
      category_id: "science"

# 科学のメモのサブカテゴリ
  # 物理のメモ
  - scope:
      path: "_science_articles/physics"
    values:
      sub_category_id: "physics"

################################## 人生
  - scope:
      path: "_life_articles"
    values:
      layout: "life_article_layout"
      category_id: "life"

# 人生のサブカテゴリ
  # 断捨離
  - scope:
      path: "_life_articles/minimalism"
    values:
      sub_category_id: "minimalism"

  # 態度
  - scope:
      path: "_life_articles/attitude"
    values:
      sub_category_id: "attitude"

  # 目的
  - scope:
      path: "_life_articles/purpose"
    values:
      sub_category_id: "purpose"

  # 失敗
  - scope:
      path: "_life_articles/failure"
    values:
      sub_category_id: "failure"

  # 時間管理
  - scope:
      path: "_life_articles/time_management"
    values:
      sub_category_id: "time_management"

################################## 読書
  - scope:
      path: "_reading_articles"
    values:
      layout: "reading_article_layout"
      category_id: "reading"

# 読書のサブカテゴリ
  # 読書の魅力
  - scope:
      path: "_reading_articles/charmpoint"
    values:
      sub_category_id: "charmpoint"
  # 読書法
  - scope:
      path: "_reading_articles/method"
    values:
      sub_category_id: "method"

################################## 全メモのリスト
  - scope:
      path: "all"
    values:
      layout: "all_layout"
      category_id: "all"

# コレクションの設定
collections_dir: collections

collections:
  # 更新履歴
  history:

  # チャプター
  it_excel_key_combination_chapters:
  it_git_command_chapters:
  it_java_database_control_chapters:
  it_java_enums_cannot_be_inherited_but_interfaces_can_chapters:
  it_java_map_multiple_key_chapters:
  it_linux_command_history_next_chapters:
  it_other_term_chapters:
  it_problem_hot_summer_day_chapters:
  it_python_grammar_chapters:
  it_ruby_grammar_chapters:
  it_ruby_string_chapters:
  it_sqlserver_conversion_functions_chapters:
  it_sqlserver_ddl_chapters:
  it_sqlserver_duplicate_the_database_in_the_same_instance_chapters:
  it_sqlserver_logical_name_chapters:
  it_sqlserver_rank_denserank_rownumber_chapters:
  it_sqlserver_tips_chapters:
  it_vba_database_control_chapters:
  it_vba_type_chapters:
  it_windows_tips_chapters:
  life_attitude_expectations_chapters:
  life_failure_uneasiness_chapters:
  life_minimalism_discard_chapters:
  life_purpose_die_with_zero_chapters:
  life_purpose_ultimate_goal_chapters:
  life_time_management_item_202103_chapters:
  reading_charmpoint_about_book_chapters:
  reading_method_read_from_ending_chapters:
  science_physics_time_chapters:

  # 以下、出力するコレクション ---------------------
  #   ※output:true じゃないコレクションをそれより前に定義しておかないと
  #     コレクション内から、コレクションを呼び出したときに、Liquid Tagsがなぜか利用できないので
  #     注意すること(201229)

  # IT記事
  it_articles:
    output: true
    permalink: /it/:path

  # 科学の記事
  science_articles:
    output: true
    permalink: /science/:path

  # 人生の記事
  life_articles:
    output: true
    permalink: /life/:path

  # 読書の記事
  reading_articles:
    output: true
    permalink: /reading/:path

# 除外ファイル/ディレクトリ
exclude:
  - todo.txt
  - _scripts
